name: Build

on:
        - push
        - pull-request

jobs:
        build:
                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v2
                        - name: Set on openJDK
                          uses: actions/setup-java@v1
                          with:
                                  java-version: '16'
                        - name: Build with Gradle
                          run: make build
